### ISSUE TITLE
Loading pymzn throws syntax error in __init__.py

### ISSUE THREAD

**Issue by indrajitsg** [paolodragone/pymzn#12]
Hi,
I am using Anaconda Python 2.7.12 in Windows 8.1. I installed pymzn with pip as instructed. When I tried to import the library, it throws me this error:

    Traceback (most recent call last):
      File "<pyshell#3>", line 1, in <module>
        import pymzn
      File "C:\Users\Indrajit\Anaconda2\lib\site-packages\pymzn\__init__.py", line 114
        args.func(**{**vars(args), **args.solver_args})
                      ^
    SyntaxError: invalid syntax

Please look into it.

Regards,
Indrajit

**Comment by HelgeS** [comment]
Installing via pip gets the Python 3 version of pymzn, which is unfortunately not working with python 2.

You can install the python 2-compatible branch by: `pip install git+https://github.com/paolodragone/pymzn.git@python2`
However, it is not up-to-date with the main development, e.g. the example from the readme is not working.

@paolodragone is there a specific reason to have two codebases for python 2 and 3? So far I identified only the subprocess module to be relying on the Python 3-specific version. Are there further dependencies?

**Comment by indrajitsg** [comment]
I tried. This is the error I am getting:

    Collecting git+https://github.com/paolodragone/pymzn.git@python2
      Cloning https://github.com/paolodragone/pymzn.git (to python2) to c:\users\indraj~2.sen\appdata\local\temp\pip-4gayvz-build
      Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/paolodragone/pymzn.git c:\users\indraj~2.sen\appdata\local\temp\pip-4gayvz-build
    Cannot find command 'git'

I do have Git Bash installed.

Regards,
Indrajit

**Comment by HelgeS** [comment]
You need to have the `git` command on your `%PATH%` variable, so it can be found by pip (see [here](http://stackoverflow.com/questions/29565779/cannot-find-command-git-windows)).

I also found another alternative: `pip install https://github.com/paolodragone/pymzn/archive/python2.zip`, this installs the same version as the command above, but does not require git to be available.

**Comment by paolodragone** [comment]
Hi, sorry about the lack of support for both Windows and Python 2. I personally use Python 3 on Linux so I often overlook other platforms. I'll try to put some effort on those now that there are more people using pymzn on them.
@HelgeS As said, I mainly develop in python 3.5, so I often make use of syntactic constructs of the newer versions of python, that is why I keep python 2 and 3 versions on separate branches.
