### ISSUE TITLE
'CalledProcessError' object has no attribute 'stderr'

### ISSUE THREAD

**Issue by HristoBuyukliev** [paolodragone/pymzn#19]
Hello,

I'm on ubuntu 14, and use python2.7 (yeah I know, we have an old-ish system). I installed pymzn by using "pip install git+https://github.com/paolodragone/pymzn.git@python2", and for  minizinc, I cloned the official github repo and ran the instructions in INSTALL.txt. If I run the following code:

    import pymzn
    import pandas as pd 
    import os

    MINIZINC_PATH = "/home/hristo/libminizinc/build"
    TIMEOUT = 300

    skills = pd.read_csv('data/skills.csv')
    people = skills.name
    skills = skills.loc[:, skills.columns != 'name']
    demand_forecast = pd.read_csv('data/demand_forecast.csv')
    hours_num = 24
    days_num = 3
    people_num = 4

    in_data = {
        'days_num': days_num,
        'D' : list(range(days_num)),
        'hours_num': hours_num,
        'H': list(range(hours_num)),
        'skills_num': skills.shape[1],
        'positions_num': skills.shape[1], # same as skills,
        'Pskl': skills.values,
        'Ppattern': list(range(people_num)),
        'people_pattern_num': people_num,
        'Fct_reduced': demand_forecast.values,
        'skill_pattern_counts': [15,15,15,15],
        'P_salary': list(range(people_num)) + [3,2,3,2]
    }

    pymzn.dict2dzn(in_data, fout='data/in_data.dzn')

    solver = pymzn.Chuffed(os.path.join(MINIZINC_PATH, 'mzn-chuffed'),
                       os.path.join(MINIZINC_PATH, 'fzn-chuffed'))
    res = pymzn.minizinc('simple_model_warehouse_no_crews.mzn',
                         data=in_data,
                         solver=solver, timeout=TIMEOUT)

I get the following error:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-1-13a2d44180ca> in <module>()
         38 res = pymzn.minizinc('simple_model_warehouse_no_crews.mzn',
         39                      data=in_data,
    ---> 40                      solver=solver, timeout=TIMEOUT)

    /home/hristo/mlenv/local/lib/python2.7/site-packages/pymzn/mzn/minizinc.pyc in minizinc(mzn, *dzn_files, **solver_args)
        230             out = solver.solve(mzn_file, *dzn_files, data=data,
        231                         include=include, timeout=timeout, output_mode=u'item',
    --> 232                         all_solutions=all_solutions, **solver_args)
        233             solns, complete = split_solns(out)
        234             solns = list(imap(dzn2dict, solns))

    /home/hristo/mlenv/local/lib/python2.7/site-packages/pymzn/mzn/solvers.pyc in solve(self, mzn_file, *dzn_files, **kwargs)
        486                 raise RuntimeError(process.stderr)
        487         except CalledProcessError, err:
    --> 488             log.exception(err.stderr)
        489             raise RuntimeError(err.stderr)
        490         return out

    AttributeError: 'CalledProcessError' object has no attribute 'stderr'

**Comment by paolodragone** [comment]
Hi,
Sorry for the delay. Unfortunately the python2 branch is a bit outdated and not very well tested. I'll try to take a look at it in the next weeks.

**Comment by HristoBuyukliev** [comment]
Hey,
No problem at all. It actually forced me to update my system and works fine now :) However, the whole minizinc language is very annoying to set-up/use, so I'll probably move to google's or-tools.

**Comment by paolodragone** [comment]
Oh ok! I'll keep the issue open as a reminder! :)

**Comment by paolodragone** [comment]
Python 2 is no longer supported. PyMzn now requires Python >= 3.5.
