### ISSUE TITLE
NameError / typo in master

### ISSUE THREAD

**Issue by Nitrogenycs** [paolodragone/pymzn#23]
Hey,

thanks for creating this project!

When running with wait=False, I ran into a "NameError: name 'solver_proces' is not defined". The reason are typos in minizinc.py at lines 340 +341 (see https://github.com/paolodragone/pymzn/blob/a5de87f9b7fc2732fdd3cdc6640b681f46fdafdb/pymzn/mzn/minizinc.py#L340 ). In both lines the variable name should read 'solver_proces**s**', right now there is an 's' missing at the end.

Best,
-Matthias

**Comment by paolodragone** [comment]
Thank you for spotting this!
Fixed in a2c3b867b95.

**Comment by Nitrogenycs** [comment]
Thanks for fixing!
