### ISSUE TITLE
Temporary files not deleted

### ISSUE THREAD

**Issue by Nitrogenycs** [paolodragone/pymzn#25]
Hi,

The named temporary files that are created never seem to get deleted (delete=False). This causes the files to pile up in my /tmp dir. I've found the `_cleanup` function, but it doesn't seem to get invoked. One reason could be exception raising and the stream never being iterated at all. I think there should be some kind of context manager to prevent this. I'm also not sure how this should work with the wait=False mode.

**Comment by paolodragone** [comment]
So the model you are running is raising exception?
If so, this is the expected behavior.
The idea is that when an error raises PyMzn does not delete the model so you can check where the error is.

**Comment by Nitrogenycs** [comment]
Ahh, I get it now, thank you. I would have expected it only keeps files around when keep=True. I'll close this  issue as "by design" then.
