### ISSUE TITLE
enable gecode multithreading by default

### ISSUE THREAD

**Issue by stefanoteso** [paolodragone/pymzn#3]
Hi,

I think that it would make sense to enable gecode's parallel execution by default (it is set to single-threaded right now). This way users would get the maximum possible performance automatically, without having to mess with the arguments of fzn_gecode().

Thanks!

**Comment by paolodragone** [comment]
I prefer to stick with Gecode's default behaviour which is to use one thread to solve a problem. On the other hand I will probably add the possibility to specify the pymzn and solvers parameter values in a config file to make it easier to configure and have to write it only once for every call to pymzn.
