### ISSUE TITLE
Incorrect preprocessing of `.mzn` files, instead of `.pmzn` files

### ISSUE THREAD

**Issue by darkfishy** [paolodragone/pymzn#34]
G'day @paolodragone,
 
It seems like the latest version (`0.18.1`) is incorrectly preprocessing MZN files and treats them like PMZN file.

More specifically, while processing `.mzn` files, it is removing all characters following the first `%` character it encounters in a line, even if that character is within a string literal.

For instance, the following sample `.mzn` file:

```
% Use a large domain to simulate a long solving process
var 0 .. 100000: x;
solve satisfy;

%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%% Result %%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%
output [
        "\n%%%%%%%%%%%%% RESULTS %%%%%%%%%%%%%\n",
        "filled_x = \(x);\n",
        "\n%%%%%%%%%%%%%% END %%%%%%%%%%%%%%%\n",
       ];
```

gets processed into following:

```

var 0 .. 100000: x;
solve satisfy;




output [
        "\n
        "filled_x = \(x);\n",
        "\n
       ];
```

Note the empty lines above, which are basically lines where the first character was `%`. Though what is more important is that the processed file is now syntactically incorrectly (note the string literals in `output` statement); which when executed results in error (of course).

The error then thrown by that call to `pymzn.minizinc('rel/path/to/sample.mzn')` is:
```
An error occurred while executing minizinc on file

var 0 .. 100000: x;
solve satisfy;




output [
        "\n
        "filled_x = \(x);\n",
        "\n
       ];
 with command line arguments: ['--model-check-only', '-']

stdin:[line].[col]:
        "\n
           ^
Error: syntax error, unexpected end of line inside string literal
```

`[line]` and `[col]` are just placeholders I have put.

This is likely because `pymzn.mzn.minizinc._minizinc_preliminaries()` is calling `pymzn.mzn.minizinc.preprocess_model()` irrespective of the file extension.

System Setup:
  * OS: MacOS Mojave 10.14.3  
  * Python: 3.7.0  
  * PyMZN: 0.18.1  
  * MiniZinc: 2.2.3  
  * Gecode: 6.1.0

**Comment by paolodragone** [comment]
Hi @darkfishy, thanks for spotting this!
I just fixed it in 9624327.
It was not about bad processing of `pmzn`, but the fact that during preporcessing I was removing comments, so anything starting with `%`, regardless of it being in a string or not. Now I simply do not attempt to remove comments in the preprocessing.
Let me know if you find anything else! :)
Cheers!

**Comment by darkfishy** [comment]
No worries mate. Thanks for fixing it so quickly. I didn't think of looking it further.
I'll test it again in the morning (mine :-) )

Said so, I do like the idea of removing comments to reduce size; not that it made much difference to the solver when I tested last time.

**Comment by darkfishy** [comment]
This works now. Thanks again.
