### ISSUE TITLE
parallel argument leads to type error

### ISSUE THREAD

**Issue by jschelbert** [paolodragone/pymzn#39]
I've run in a fairly similar bug like #35 - this time for solver argument `parallel`. Might probably also be an issue for `seed` and `num_solutions` as they are not converted to a string.
Solved it for the time being by setting 
```python
        if num_solutions is not None:
            args += ['-n', str(num_solutions)]
        if free_search:
            args.append('-f')
        if parallel is not None:
            args += ['-p', str(parallel)]
        if seed is not None:
            args += ['-r', str(seed)]
```
in the `Solver` class.
If I got time this weekend I could try to propose a PR.

**Comment by paolodragone** [comment]
Yep, good catch! thank you for reporting this.
I'll fix it as soon as possible.
