### ISSUE TITLE
Returning "INCOMPLETE" instead a "ERROR"

### ISSUE THREAD

**Issue by ceandrade** [paolodragone/pymzn#43]
Hi, 

When the model or the data has a problem, pymzn.minizinc() returns `INCOMPLETE` instead a `ERROR`. Let's see in the terminal:

```bash
$ cat model.mzn 
set of 0..10: values;
array[values] of var 0..1: x;
solve minimize sum(x);
values = {1, 3, 5};

$ minizinc --solver COIN-BC model.mzn 
MiniZinc: evaluation error: 
 ...../model.mzn:2:
  in variable declaration for 'x'
  array index set must be contiguous range
```

Which is OK calling minizinc directly. Now, let's see using pymzn:

```python
In [1]: import pymzn                                                                                                                                    
In [2]: result = pymzn.minizinc(mzn="model.mzn", solver=pymzn.cbc)                                                                                      
In [3]: result                                                                                                                                          
Out[3]: <Solutions: INCOMPLETE>
In [4]: result.status == pymzn.Status.ERROR                                                                                                             
Out[4]: False
```

The documentation is a little bit vague, but it says that status `INCOMPLETE` represents an incomplete solution stream. I don't know what this means precisely. Assuming that we have status `COMPLETE` (that assumes that an optimum solution is found) and an `ERROR` saying that a "Generic error in the execution of the solver," I would tell that incomplete means that the search is incomplete, i.e., we have no errors (since erros are supposed to be reported by `ERROR` flag), but only a situation where we could not complete the search (maybe do not find a feasible solution).

However, note that models errors should be treated as `ERROR` since we have an actual error, not an incomplete search, or special condition in the search.

**Comment by paolodragone** [comment]
Hi @ceandrade, thanks for reporting this. This happens because the error is raised at flattening time, so no error flag (`=====ERROR=====`) is printed on standard output (commonly printed at solving time), and so it's not caught during solution parsing. PyMzn looks for these errors before launching the full MiniZinc run by doing model checking and instance checking (i.e. running MiniZinc with `--model-check-only` and `--instance-check-only`). However, quite surprisingly, in your case MiniZinc does not fail during model nor instance checking, I'm not exactly sure why. I'll make a fix for this in PyMzn.

**Comment by ceandrade** [comment]
Yes, this is weird, I agree. BTW, my minizinc version is 

```bash
$ minizinc --version
MiniZinc to FlatZinc converter, version 2.3.1, build 70205949
Copyright (C) 2014-2019 Monash University, NICTA, Data61
```

@paolodragone I will doubt check this and may open a ticket on minizinc repo.

Thanks for your fast reply!

**Comment by ceandrade** [comment]
FYI: https://github.com/MiniZinc/libminizinc/issues/313

**Comment by paolodragone** [comment]
Thanks. Anyway, now it is solved in the master branch. I'll make a release soon.

**Comment by Dekker1** [comment]
@paolodragone The best way of ensuring the process finished successfully would be to check the exit code. When the exit code is non-zero then an error has occurred during execution.

**Comment by paolodragone** [comment]
Hi @Dekker1, thank you for the tip, I'll make use of it!
