### ISSUE TITLE
Select  mzn-g12mip instead of fzn-gecode

### ISSUE THREAD

**Issue by silgon** [paolodragone/pymzn#9]
I think the subject is self explanatory. You see, the Minizinc tutorial uses always "mzn-g12fd" or "mzn-g12mip" and not "fzn-gecode", the problem is that with "fzn-gecode" is taking a long time to solve the problem, I would like to be able to change it.

**Comment by paolodragone** [comment]
Hi,
The G12 solvers are not supported by PyMzn at the moment.
You could implement the support yourself, more info [here](http://paolodragone.com/pymzn/reference/solvers/index.html).
Still, I think those solvers are pretty much discontinued (last release was in 2012), I advice you to use some actively developed solvers, like [Opturion](http://www.opturion.com/) or [others](http://www.minizinc.org/software.html).
Cheers.

**Comment by silgon** [comment]
I'm new at MiniZinc (I started on Monday =P), I was asking just because it was more convenient to run something that I knew it was faster.
In any case thanks for the insight. I'm closing the issue. However I think it would be a nice feature the for early learners like me.
Thanks for the repository!

**Comment by silgon** [comment]
This is the code that I created. It took me a while because I had no idea about how `--globals-dir` was used, which it is not well specified in the documentation of minizinc about the command `mzn-g12mip`. 

```python
class G12MIP(Solver):
    def __init__(self, path=None):
        super().__init__(True, True, globals_dir='linear')
        self.cmd = path or 'flatzinc'

    def solve(self, fzn_file, **kwargs):
        args = [self.cmd, "-b","mip",fzn_file]
        process = run(args)
        return process.stdout
```
Hopefully it is useful to somebody at some point. =)

**Comment by silgon** [comment]
Hello. One little question, the code above was working fine in version `pymzn==0.11.4`, now you have version `pymzn==0.13` and it throws an error. Here the whole message error.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pymzn/_mzn/_minizinc.py", line 302, in mzn2fzn
    run(args)
  File "/usr/local/lib/python3.5/dist-packages/pymzn/bin.py", line 117, in run
    process.check_returncode()
  File "/usr/local/lib/python3.5/dist-packages/pymzn/bin.py", line 68, in check_returncode
    super().check_returncode()
  File "/usr/lib/python3.5/subprocess.py", line 659, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '['mzn2fzn', '-G', 'linear', '/tmp/pymzn_17qejmpa.mzn', '/tmp/pymzn_17qejmpa_data.dzn']' returned non-zero exit status 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "percent_change.py", line 40, in <module>
    res_t_2 = mzn.minizinc("percent_simple.mzn", data={"w":w_t_2}, solver=G12MIP())
  File "/usr/local/lib/python3.5/dist-packages/pymzn/_mzn/_minizinc.py", line 167, in minizinc
    stdlib_dir=stdlib_dir)
  File "/usr/local/lib/python3.5/dist-packages/pymzn/_mzn/_minizinc.py", line 305, in mzn2fzn
    raise RuntimeError(err.stderr) from err
RuntimeError: /tmp/pymzn_17qejmpa.mzn:21:
solve minimize error;*1000)/1000)++"\t" | i in n_iter ];)++"\t" | i in n_iter ];
                     ^
Error: syntax error, unexpected *, expecting end of file
```
I was playing around today and I encountered that problem.

**Comment by paolodragone** [comment]
Hi! Yes, sorry, I've been modifying a bit the library, I am trying to simplify many things that now are a bit clunky. So, I am actually going to release a big update soon (hopefully by the end of the week), I'll try to include the code for G12MIP as well.

**Comment by silgon** [comment]
Ok. In any case I decided to downgrade for the moment (since the old code was already working).

**Comment by paolodragone** [comment]
Hi, as promised I made a new release including the code for the G12 solvers. I haven't been able to test it in depth so please let me know if there is any bug! :)

**Comment by silgon** [comment]
I'll be testing it most probably at the beginning of next week. I'll let you know. Thanks! =)

**Comment by silgon** [comment]
Sorry for not replying before. I'm testing now I don't get it to run. I'm doing something wrong probably. I'm looking at http://paolodragone.com/pymzn/reference/solvers/generated/pymzn.G12MIP.html#pymzn.G12MIP

The simplest thing I tried was to invoke the new class `G12MIP` instead of my class.
```
from pymzn import G12MIP
result= mzn.minizinc("myprogram.mzn", data={"a":array_variable}, solver=G12MIP())
```
However, for my program it raises the following error:
```
/tmp/pymzn_vu2xaudb.mzn:21:
solve minimize error;*1000)/1000)++"\t" | i in n_iter ];)++"\t" | i in n_iter ];
                     ^
Error: syntax error, unexpected *, expecting end of file
```
It seems that my program is not parsed correctly by flatzinc for some reason. It is probabably the same error that I showed you before, but now with the new version of `pymzn`.

**Comment by paolodragone** [comment]
Looking it again, it doesn't look like an error of G12MIP but rather an error of the minizinc or mzn2fzn functions. Could you maybe attach the minizinc model that generates the error, or send me a gist or send it to me by email?

**Comment by silgon** [comment]
Yeah, it seems an error from minizinc or flatzinc, however with the pymzn version `0.11.4` with the class I included in the [previous comment](https://github.com/paolodragone/pymzn/issues/9#issuecomment-276106674) it works with no problem. Which means that it should be probably some flag. I could create a simple code to send it to you, however I don't have that much time today to do so. I tested the new version because I didn't want to procrastinate anymore something I said I would do =).

**Comment by silgon** [comment]
Hey, @paolodragone I was trying (just now) to download the version that's working for me  `0.11.4` but I'm not able to download it anymore. Did you delete it from [the repository site](https://pypi.python.org/pypi/pymzn/0.14.9)? Is there a way to put it back? Thanks in advance.

**Comment by silgon** [comment]
I'm just testing your last version `0.14.9`. In which  `G12MIP` works now, however, you don't display the error as a result of the function. The error can be useful if you have another function depending result value of the one in `minizinc`.

**Comment by paolodragone** [comment]
G12 solvers are no longer supported by PyMzn (they are [deprecated](https://www.minizinc.org/doc-2.2.3/en/installation.html?highlight=g12) by MiniZinc too).
